import styles from "../styles/Home.module.css";
import Menu from "../components/Menu"
import Head from "next/head"


export default function Home() {
  return (
    <>
    
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <main className={styles.main}>
      <Menu loggedIn={true} desktop={false} />
      <div className={styles.wrapper}>
        <p>Hello World! Test1 Test2</p>
      </div>
    </main>
    
    </>
  );
}
